server:
  port: 8080
  servlet:
    context-path: /user-registry-service

spring:
  datasource:
    url: jdbc:h2:mem:registry-db
  h2:
    console:
      enabled: true
      path: /h2-console

security:
    jwt:
      secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
      expiration-time: 60000 #expire in a min
    #  expiration-time: 3600000

